server:
  port: 9080

  datasource:
    url: jdbc:mariadb//localhost:3306/photocommunity
    username: photocommunity
    password: 1234

mybatis:
  type-aliases-package: {mapper resultType}
  mapper-locations: mybatis/mapper/**/*.xml

